### ISSUE TITLE
SIGMA和epoch取值

### ISSUE THREAD

**Issue by yangpyoung** [ChunLiu-cs/LLMEmbed-ACL2024#1]
想请问下SIGMA和epoch取值大小建议，dataset 大小在2000多，label class_num为11

**Comment by ChunLiu-cs** [comment]
您好，邮件已收到，我会及时处理的，祝好！ヾ(^▽^*)))

**Comment by yangpyoung** [comment]
您好，还想请问下针对推理阶段的inference的话，还需要3个阶段都走一遍吗？这样的话推理时间会有点长

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ChunLiu ***@***.***&gt;
发送时间: 2024年7月4日 17:40
收件人: ChunLiu-cs/LLMEmbed-ACL2024 ***@***.***&gt;
抄送: yangpyoung ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ChunLiu-cs/LLMEmbed-ACL2024] SIGMA和epoch取值 (Issue #1)





 您好，邮件已收到，我会及时处理的，祝好！ヾ(^▽^*)))

**Comment by yangpyoung** [comment]
已解决谢谢

**Comment by ChunLiu-cs** [comment]
您好，最近较忙回复不及时，很高兴您能解决问题。
